# Assignment #5 - Jackie Woodlief & Jeff Sharpe

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder, Imputer
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

/home/shelob/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

# Big Picture

Based on the past performance of the 2015 flight dataset (from assignment 3), we saw that the non-linear SVM's performed well on the data set; however, that was due in part because we reduced the size of our data set by quite a bit. If the Gaussian RBF with grid search can yield such good results on a small - medium size and complex data set, we can imagine that since neural networks are better at dealing with large, complex data sets, then the performance may even improve. The main reason being is that there will be more data. With such a big, complex data set, a neural network seems like the most appropriate approach.

compare 2 different airlines, maybe

# Get the Data / Info

We are using the flight data set because it is our largest data set, it's massive, with almost 6,000,000 rows and 31 columns. In the past we couldn't use the entire data set because it was too big for our computers to handle efficiently. In addition, we already know that this is a complex data set due to our past assignments involving it and visualizing it.



https://www.kaggle.com/usdot/flight-delays/data

Click on the above link, and download flights.csv, as that is the data set I used for this assignment!

In [2]:
 #Let's read in our data

flights_data = pd.read_csv("flights.csv")

/home/shelob/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
train_set_throwaway, flights = train_test_split(flights_data, test_size = 0.017, random_state = 42)
del train_set_throwaway # since we don't them, we can go ahead and delete them from the memory!

In [4]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 98925 entries, 1508570 to 450748
Data columns (total 31 columns):
YEAR                   98925 non-null int64
MONTH                  98925 non-null int64
DAY                    98925 non-null int64
DAY_OF_WEEK            98925 non-null int64
AIRLINE                98925 non-null object
FLIGHT_NUMBER          98925 non-null int64
TAIL_NUMBER            98666 non-null object
ORIGIN_AIRPORT         98925 non-null object
DESTINATION_AIRPORT    98925 non-null object
SCHEDULED_DEPARTURE    98925 non-null int64
DEPARTURE_TIME         97460 non-null float64
DEPARTURE_DELAY        97460 non-null float64
TAXI_OUT               97403 non-null float64
WHEELS_OFF             97403 non-null float64
SCHEDULED_TIME         98925 non-null float64
ELAPSED_TIME           97137 non-null float64
AIR_TIME               97137 non-null float64
DISTANCE               98925 non-null int64
WHEELS_ON              97339 non-null float64
TAXI_IN                97339 non-null float64
SCHEDULED_ARRIVAL      98925 non-null int64
ARRIVAL_TIME           97339 non-null float64
ARRIVAL_DELAY          97137 non-null float64
DIVERTED               98925 non-null int64
CANCELLED              98925 non-null int64
CANCELLATION_REASON    1538 non-null object
AIR_SYSTEM_DELAY       18163 non-null float64
SECURITY_DELAY         18163 non-null float64
AIRLINE_DELAY          18163 non-null float64
LATE_AIRCRAFT_DELAY    18163 non-null float64
WEATHER_DELAY          18163 non-null float64
dtypes: float64(16), int64(10), object(5)
memory usage: 24.2+ MB

In [5]:
flights.describe()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
count,98925.0,98925.000000,98925.000000,98925.000000,98925.000000,98925.000000,97460.000000,97460.000000,97403.000000,97403.000000,...,98925.000000,97339.000000,97137.000000,98925.000000,98925.000000,18163.000000,18163.000000,18163.000000,18163.000000,18163.000000
mean,2015.0,6.516998,15.720718,3.907506,2179.155876,1328.242568,1333.406146,9.363411,16.043756,1355.475509,...,1491.153035,1475.228541,4.424061,0.002527,0.015547,13.541540,0.098552,18.807080,23.414524,2.811925
std,0.0,3.407106,8.782202,1.986356,1764.577362,483.378648,495.865855,36.999720,8.939410,497.354082,...,507.813903,525.762371,39.290706,0.050208,0.123716,27.541651,2.347444,49.214433,42.637061,20.486393
min,2015.0,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000,-36.000000,1.000000,1.000000,...,1.000000,1.000000,-70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2015.0,4.000000,8.000000,2.000000,730.000000,919.000000,921.000000,-5.000000,11.000000,935.000000,...,1109.000000,1058.000000,-13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2015.0,7.000000,16.000000,4.000000,1687.000000,1325.000000,1329.000000,-2.000000,14.000000,1341.000000,...,1518.000000,1511.000000,-5.000000,0.000000,0.000000,2.000000,0.000000,2.000000,3.000000,0.000000
75%,2015.0,9.000000,23.000000,6.000000,3245.000000,1730.000000,1738.000000,7.000000,19.000000,1752.000000,...,1915.000000,1915.000000,8.000000,0.000000,0.000000,18.000000,0.000000,18.000000,29.000000,0.000000
max,2015.0,12.000000,31.000000,7.000000,7438.000000,2359.000000,2400.000000,1576.000000,225.000000,2400.000000,...,2359.000000,2400.000000,1557.000000,1.000000,1.000000,536.000000,142.000000,1557.000000,817.000000,865.000000

In [6]:
flights.head(5)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
1508570,2015,4,7,2,EV,4900,N759EV,FWA,DTW,1340,...,1423.0,-13.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
363270,2015,1,24,6,AS,611,N413AS,LAS,SEA,1910,...,2133.0,-12.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3003945,2015,7,8,3,WN,1483,N463WN,OAK,SEA,630,...,812.0,-8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2291425,2015,5,26,2,WN,193,N7745A,STL,DAL,810,...,1222.0,152.0,0,0,NaN,0.0,0.0,0.0,152.0,0.0
2973084,2015,7,6,1,UA,253,N213UA,IAH,HNL,1000,...,1316.0,-2.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Let's make a copy just in case we need to refer back to the original

copy = pd.DataFrame.copy(flights)

In [8]:
# Based on the correlation matrix of airlines, used from a previous run, we determined that these features
# we not very correlated with determining the airline, so we decided to drop these features

copy = copy.drop("CANCELLATION_REASON", 1)
# copy = copy.drop("TAIL_NUMBER", 1)
copy = copy.drop("YEAR", 1)
copy = copy.drop("DAY", 1)
copy = copy.drop("MONTH", 1)
# copy = copy.drop("FLIGHT_NUMBER", 1)
copy = copy.drop("DAY_OF_WEEK", 1)
copy = copy.drop("DIVERTED", 1)
copy = copy.drop("CANCELLED", 1)
copy = copy.drop("AIR_SYSTEM_DELAY", 1)
copy = copy.drop("SECURITY_DELAY", 1)
copy = copy.drop("WHEELS_OFF", 1)
copy = copy.drop("SCHEDULED_DEPARTURE", 1)
copy = copy.drop("WEATHER_DELAY", 1)
copy = copy.drop("AIRLINE_DELAY", 1)
copy = copy.drop("WHEELS_ON", 1)
copy = copy.drop("SCHEDULED_ARRIVAL", 1)
copy = copy.drop("ARRIVAL_TIME", 1)
copy = copy.drop("DEPARTURE_TIME", 1)
copy = copy.drop("LATE_AIRCRAFT_DELAY", 1)
copy = copy.drop("ARRIVAL_DELAY", 1)
copy = copy.drop("DEPARTURE_DELAY", 1)

In [9]:
# copy = copy.reset_index(drop = True)

In [10]:
copy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 98925 entries, 1508570 to 450748
Data columns (total 11 columns):
AIRLINE                98925 non-null object
FLIGHT_NUMBER          98925 non-null int64
TAIL_NUMBER            98666 non-null object
ORIGIN_AIRPORT         98925 non-null object
DESTINATION_AIRPORT    98925 non-null object
TAXI_OUT               97403 non-null float64
SCHEDULED_TIME         98925 non-null float64
ELAPSED_TIME           97137 non-null float64
AIR_TIME               97137 non-null float64
DISTANCE               98925 non-null int64
TAXI_IN                97339 non-null float64
dtypes: float64(5), int64(2), object(4)
memory usage: 9.1+ MB

In [11]:
encoder = LabelEncoder() #AIRLINE, DESTINATION_AIRPORT, ORIGIN_AIRPORT

In [16]:
airline_cat = copy["AIRLINE"]
destination_cat = copy["DESTINATION_AIRPORT"]
origin_cat = copy["ORIGIN_AIRPORT"]
tail_cat = copy["TAIL_NUMBER"]
flight_cat = copy["FLIGHT_NUMBER"]

In [17]:
destination_cat = destination_cat.apply(str)
origin_cat = origin_cat.apply(str)
flight_cat = flight_cat.apply(str)
tail_cat = tail_cat.apply(str)

In [18]:
# destination_cat = destination_cat.fillna('Other Dest')
# origin_cat = origin_cat.fillna('Other Org')

In [19]:
airline_cat_encoded = encoder.fit_transform(airline_cat)
destination_cat_encoded = encoder.fit_transform(destination_cat)
origin_cat_encoded = encoder.fit_transform(origin_cat)
tail_cat_encoded = encoder.fit_transform(tail_cat)
flight_cat_encoded = encoder.fit_transform(flight_cat)

In [20]:
copy["AIRLINE"]= airline_cat_encoded
copy["DESTINATION_AIRPORT"] = destination_cat_encoded
copy["ORIGIN_AIRPORT"] = origin_cat_encoded
copy["FLIGHT_NUMBER"] = flight_cat_encoded
copy["TAIL_NUMBER"] = tail_cat_encoded

In [21]:
copy.head(3)

,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,TAXI_OUT,SCHEDULED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,TAXI_IN
1508570,4,4229,3255,387,362,13.0,56.0,48.0,30.0,128,5.0
363270,1,5435,1551,440,545,14.0,155.0,155.0,131.0,867,10.0
3003945,13,537,1712,488,545,8.0,110.0,106.0,92.0,672,6.0

In [22]:
imputer = Imputer(strategy = "median")

In [24]:
imputer.fit(copy)
X = imputer.transform(copy)
transform_copy = pd.DataFrame(X, columns = copy.columns)
transform_copy

,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,TAXI_OUT,SCHEDULED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,TAXI_IN
0,4.0,4229.0,3255.0,387.0,362.0,13.0,56.0,48.0,30.0,128.0,5.0
1,1.0,5435.0,1551.0,440.0,545.0,14.0,155.0,155.0,131.0,867.0,10.0
2,13.0,537.0,1712.0,488.0,545.0,8.0,110.0,106.0,92.0,672.0,6.0
3,13.0,1033.0,3384.0,560.0,350.0,6.0,100.0,99.0,85.0,546.0,8.0
4,10.0,1700.0,545.0,418.0,410.0,16.0,498.0,488.0,461.0,3904.0,11.0
5,3.0,424.0,4550.0,414.0,289.0,13.0,70.0,49.0,28.0,151.0,8.0
6,10.0,510.0,664.0,418.0,571.0,13.0,137.0,120.0,100.0,787.0,7.0
7,1.0,5893.0,2013.0,543.0,507.0,11.0,171.0,163.0,145.0,1107.0,7.0
8,0.0,0.0,3509.0,432.0,444.0,34.0,385.0,381.0,341.0,2475.0,6.0
9,5.0,5981.0,530.0,223.0,71.0,9.0,249.0,222.0,204.0,1607.0,9.0
10,13.0,1682.0,3920.0,468.0,320.0,13.0,115.0,92.0,72.0,377.0,7.0
11,13.0,1398.0,3893.0,459.0,553.0,8.0,175.0,157.0,145.0,1189.0,4.0
12,13.0,2605.0,3397.0,440.0,555.0,17.0,95.0,87.0,64.0,397.0,6.0
13,13.0,622.0,3163.0,569.0,306.0,21.0,105.0,104.0,78.0,612.0,5.0
14,11.0,1091.0,2169.0,355.0,335.0,15.0,143.0,146.0,116.0,936.0,15.0
15,4.0,1749.0,2880.0,355.0,322.0,18.0,131.0,129.0,107.0,922.0,4.0
16,3.0,6153.0,847.0,308.0,484.0,31.0,205.0,196.0,161.0,1124.0,4.0
17,0.0,270.0,3857.0,459.0,355.0,14.0,183.0,174.0,148.0,985.0,12.0
18,0.0,1475.0,1758.0,470.0,355.0,10.0,175.0,139.0,118.0,853.0,11.0
19,11.0,3555.0,4215.0,504.0,536.0,10.0,340.0,315.0,302.0,2370.0,3.0
20,6.0,1044.0,1845.0,409.0,491.0,9.0,39.0,36.0,21.0,100.0,6.0
21,13.0,1298.0,2518.0,319.0,490.0,13.0,70.0,85.0,67.0,325.0,5.0
22,1.0,4326.0,3475.0,534.0,545.0,19.0,180.0,186.0,161.0,1050.0,6.0
23,0.0,3886.0,468.0,241.0,198.0,21.0,95.0,100.0,74.0,507.0,5.0
24,4.0,3949.0,152.0,375.0,353.0,44.0,80.0,98.0,49.0,199.0,5.0
25,13.0,2520.0,4383.0,468.0,571.0,8.0,220.0,191.0,178.0,1204.0,5.0
26,0.0,396.0,1413.0,291.0,355.0,14.0,65.0,118.0,94.0,190.0,6.0
27,2.0,286.0,922.0,416.0,308.0,31.0,80.0,97.0,61.0,413.0,5.0
28,4.0,3805.0,245.0,418.0,414.0,19.0,70.0,68.0,46.0,295.0,3.0
29,13.0,2131.0,3244.0,424.0,460.0,11.0,95.0,96.0,80.0,451.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...
98895,0.0,2285.0,1881.0,424.0,355.0,12.0,146.0,137.0,113.0,761.0,12.0
98896,13.0,900.0,3880.0,440.0,463.0,11.0,210.0,189.0,173.0,1521.0,5.0
98897,10.0,648.0,1076.0,194.0,87.0,10.0,174.0,172.0,147.0,1023.0,15.0
98898,7.0,2647.0,2641.0,506.0,355.0,13.0,127.0,117.0,99.0,672.0,5.0
98899,10.0,5268.0,1770.0,308.0,354.0,23.0,271.0,284.0,257.0,1754.0,4.0
98900,9.0,5810.0,4474.0,473.0,354.0,15.0,152.0,135.0,113.0,752.0,7.0
98901,0.0,154.0,1879.0,464.0,355.0,15.0,100.0,102.0,81.0,469.0,6.0
98902,9.0,3843.0,3601.0,336.0,484.0,25.0,129.0,126.0,95.0,626.0,6.0
98903,12.0,4184.0,3804.0,442.0,442.0,7.0,65.0,57.0,42.0,236.0,8.0
98904,0.0,275.0,19.0,560.0,471.0,23.0,166.0,165.0,138.0,1068.0,4.0
98905,4.0,3209.0,599.0,458.0,496.0,23.0,89.0,102.0,69.0,403.0,10.0
98906,3.0,1005.0,2913.0,383.0,362.0,16.0,172.0,172.0,150.0,1127.0,6.0
98907,9.0,4144.0,2523.0,552.0,354.0,26.0,85.0,92.0,61.0,391.0,5.0
98908,3.0,270.0,4465.0,289.0,412.0,20.0,144.0,124.0,102.0,696.0,2.0
98909,9.0,4657.0,4495.0,292.0,496.0,18.0,120.0,110.0,83.0,536.0,9.0
98910,8.0,6300.0,1975.0,569.0,289.0,9.0,82.0,78.0,62.0,406.0,7.0
98911,9.0,5793.0,606.0,379.0,444.0,7.0,79.0,73.0,49.0,209.0,17.0
98912,8.0,2903.0,2057.0,418.0,289.0,11.0,122.0,110.0,90.0,689.0,9.0
98913,4.0,5072.0,247.0,163.0,122.0,9.0,110.0,87.0,72.0,468.0,6.0
98914,9.0,4980.0,3186.0,544.0,492.0,22.0,204.0,200.0,172.0,1384.0,6.0
98915,3.0,1254.0,2943.0,362.0,461.0,13.0,162.0,152.0,127.0,957.0,12.0
98916,3.0,295.0,2538.0,482.0,286.0,15.0,339.0,326.0,305.0,2519.0,6.0
98917,8.0,6327.0,1956.0,333.0,534.0,26.0,162.0,172.0,141.0,1025.0,5.0
98918,13.0,1569.0,1557.0,306.0,571.0,12.0,105.0,98.0,82.0,612.0,4.0
98919,3.0,1593.0,2970.0,432.0,554.0,40.0,325.0,322.0,272.0,1990.0,10.0
98920,3.0,929.0,788.0,329.0,289.0,19.0,73.0,76.0,44.0,259.0,13.0
98921,2.0,4602.0,4303.0,442.0,434.0,10.0,306.0,305.0,288.0,2475.0,7.0
98922,13.0,3654.0,3710.0,461.0,507.0,9.0,230.0,209.0,195.0,1444.0,5.0
98923,4.0,5075.0,169.0,418.0,549.0,13.0,65.0,52.0,34.0,192.0,5.0
98924,0.0,613.0,1380.0,308.0,496.0,24.0,179.0,160.0,124.0,867.0,12.0

In [ ]:
%matplotlib inline
transform_copy.hist(bins = 50, figsize = (20, 15))
plt.show()

In [25]:
correlation_matrix = transform_copy.corr()

In [26]:
correlation_matrix["AIRLINE"].sort_values(ascending = False)

AIRLINE                1.000000
FLIGHT_NUMBER          0.114277
TAIL_NUMBER            0.100310
ORIGIN_AIRPORT         0.080193
DESTINATION_AIRPORT    0.079925
TAXI_IN               -0.078662
DISTANCE              -0.084596
AIR_TIME              -0.088266
SCHEDULED_TIME        -0.107270
ELAPSED_TIME          -0.111724
TAXI_OUT              -0.165614
Name: AIRLINE, dtype: float64

In [27]:
train_set, test_set = train_test_split(transform_copy, test_size = 0.2, random_state = 42)

In [28]:
train_set.head(3)

,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,TAXI_OUT,SCHEDULED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,TAXI_IN
87989,3.0,913.0,2553.0,362.0,507.0,15.0,253.0,225.0,206.0,1671.0,4.0
41349,4.0,4445.0,2536.0,333.0,484.0,18.0,125.0,124.0,101.0,622.0,5.0
26546,7.0,2393.0,2468.0,361.0,496.0,11.0,89.0,88.0,51.0,299.0,26.0

In [29]:
test_set.head(3)

,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,TAXI_OUT,SCHEDULED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,TAXI_IN
75611,11.0,4184.0,311.0,505.0,496.0,15.0,202.0,194.0,173.0,1440.0,6.0
24040,3.0,1596.0,4308.0,543.0,442.0,19.0,142.0,135.0,108.0,867.0,8.0
24138,13.0,1519.0,3904.0,461.0,350.0,8.0,150.0,129.0,115.0,793.0,6.0

In [30]:
# Now we need to split up into test and train sets based on the airline (multi-class)

y_train = train_set["AIRLINE"]
y_test = test_set["AIRLINE"]
x_test = test_set.drop("AIRLINE", 1)
x_train = train_set.drop("AIRLINE", 1)


# We need to convert to float32 due to a warning we get when we do the dnn_clf
y_train = y_train.astype('float32')
y_test = y_test.astype('float32')
x_test = x_test.astype('float32')
x_train = x_train.astype('float32')

In [ ]:
y_train.head(2)

In [ ]:
x_train.head(2)

# Large-Scale Visualization

Below we will be visualizing different aspects of our data to demonstrate that it is in fact a complex data set!

In [31]:
# Before we do anything, in order to feed the various clf's our labels, we must first convert them from
# float to integers

y_train_int = y_train.astype(int)
y_test_int = y_test.astype(int)

In [ ]:
# x_train_ds = x_train.values
# x_test_ds = x_test.values

## Fully connected network with 2 hidden layers

This is the neural network that we start with!

Also, just to note, since we don't specify here, the activation function being used is the relu!

In [ ]:
x_train.shape

In [52]:
# Since there are 14 different airlines, we need to change n_classes to 14, default seems to be 10
# NOTE: This will take a few minutes!!

feature_cols = tf.contrib.learn.infer_real_valued_columns_from_input(x_train)
dnn_clf_hidden = tf.contrib.learn.DNNClassifier(hidden_units = [300, 150], n_classes = 14, feature_columns = feature_cols)
dnn_clf_hidden = tf.contrib.learn.SKCompat(dnn_clf_hidden)
dnn_clf_hidden.fit(x_train, y_train_int, batch_size = 50, steps = 15000) # 10,000 (46%)

WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmp3a9xktor
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f8ecf17b2e8>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/tmp/tmp3a9xktor'}
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/tmp3a9xktor/model.ckpt.
INFO:tensorflow:loss = 414.89374, step = 1
INFO:tensorflow:global_step/sec: 89.4189
INFO:tensorflow:loss = 2.5871003, step = 101 (1.123 sec)
INFO:tensorflow:global_step/sec: 87.4342
INFO:tensorflow:loss = 2.2286668, step = 201 (1.143 sec)
INFO:tensorflow:global_step/sec: 90.2572
INFO:tensorflow:loss = 2.285096, step = 301 (1.107 sec)
INFO:tensorflow:global_step/sec: 91.5134
INFO:tensorflow:loss = 2.156805, step = 401 (1.093 sec)
INFO:tensorflow:global_step/sec: 89.5694
INFO:tensorflow:loss = 2.0736706, step = 501 (1.118 sec)
INFO:tensorflow:global_step/sec: 87.9726
INFO:tensorflow:loss = 1.9694927, step = 601 (1.135 sec)
INFO:tensorflow:global_step/sec: 91.8143
INFO:tensorflow:loss = 2.0701818, step = 701 (1.090 sec)
INFO:tensorflow:global_step/sec: 88.41
INFO:tensorflow:loss = 2.0249057, step = 801 (1.132 sec)
INFO:tensorflow:global_step/sec: 90.5251
INFO:tensorflow:loss = 2.0275707, step = 901 (1.104 sec)
INFO:tensorflow:global_step/sec: 88.8755
INFO:tensorflow:loss = 1.9663281, step = 1001 (1.126 sec)
INFO:tensorflow:global_step/sec: 89.7162
INFO:tensorflow:loss = 1.7462829, step = 1101 (1.115 sec)
INFO:tensorflow:global_step/sec: 89.547
INFO:tensorflow:loss = 1.8049555, step = 1201 (1.116 sec)
INFO:tensorflow:global_step/sec: 88.222
INFO:tensorflow:loss = 1.917706, step = 1301 (1.135 sec)
INFO:tensorflow:global_step/sec: 88.9146
INFO:tensorflow:loss = 1.7881236, step = 1401 (1.125 sec)
INFO:tensorflow:global_step/sec: 90.3048
INFO:tensorflow:loss = 1.6353371, step = 1501 (1.107 sec)
INFO:tensorflow:global_step/sec: 87.2091
INFO:tensorflow:loss = 2.0066733, step = 1601 (1.147 sec)
INFO:tensorflow:global_step/sec: 89.2751
INFO:tensorflow:loss = 1.8121971, step = 1701 (1.119 sec)
INFO:tensorflow:global_step/sec: 90.529
INFO:tensorflow:loss = 1.6917734, step = 1801 (1.106 sec)
INFO:tensorflow:global_step/sec: 88.114
INFO:tensorflow:loss = 1.4577234, step = 1901 (1.135 sec)
INFO:tensorflow:global_step/sec: 88.6469
INFO:tensorflow:loss = 1.6716236, step = 2001 (1.126 sec)
INFO:tensorflow:global_step/sec: 88.4274
INFO:tensorflow:loss = 2.0635624, step = 2101 (1.133 sec)
INFO:tensorflow:global_step/sec: 90.4897
INFO:tensorflow:loss = 1.9801918, step = 2201 (1.104 sec)
INFO:tensorflow:global_step/sec: 88.8486
INFO:tensorflow:loss = 1.7533673, step = 2301 (1.126 sec)
INFO:tensorflow:global_step/sec: 88.1311
INFO:tensorflow:loss = 1.4808235, step = 2401 (1.133 sec)
INFO:tensorflow:global_step/sec: 91.817
INFO:tensorflow:loss = 1.8199142, step = 2501 (1.090 sec)
INFO:tensorflow:global_step/sec: 88.7209
INFO:tensorflow:loss = 1.7921078, step = 2601 (1.128 sec)
INFO:tensorflow:global_step/sec: 90.798
INFO:tensorflow:loss = 1.7800815, step = 2701 (1.101 sec)
INFO:tensorflow:global_step/sec: 92.1493
INFO:tensorflow:loss = 1.6874585, step = 2801 (1.085 sec)
INFO:tensorflow:global_step/sec: 90.4207
INFO:tensorflow:loss = 1.8308668, step = 2901 (1.106 sec)
INFO:tensorflow:global_step/sec: 90.9915
INFO:tensorflow:loss = 2.1047654, step = 3001 (1.098 sec)
INFO:tensorflow:global_step/sec: 91.0913
INFO:tensorflow:loss = 1.8032379, step = 3101 (1.098 sec)
INFO:tensorflow:global_step/sec: 93.3003
INFO:tensorflow:loss = 1.9488785, step = 3201 (1.074 sec)
INFO:tensorflow:global_step/sec: 90.0799
INFO:tensorflow:loss = 1.6466591, step = 3301 (1.110 sec)
INFO:tensorflow:global_step/sec: 91.5038
INFO:tensorflow:loss = 1.5963141, step = 3401 (1.091 sec)
INFO:tensorflow:global_step/sec: 91.4824
INFO:tensorflow:loss = 1.7507535, step = 3501 (1.095 sec)
INFO:tensorflow:global_step/sec: 88.7166
INFO:tensorflow:loss = 1.7625101, step = 3601 (1.127 sec)
INFO:tensorflow:global_step/sec: 91.7096
INFO:tensorflow:loss = 1.9104457, step = 3701 (1.091 sec)
INFO:tensorflow:global_step/sec: 92.3139
INFO:tensorflow:loss = 1.7319418, step = 3801 (1.082 sec)
INFO:tensorflow:global_step/sec: 91.7631
INFO:tensorflow:loss = 1.5068784, step = 3901 (1.089 sec)
INFO:tensorflow:global_step/sec: 90.9101
INFO:tensorflow:loss = 1.653604, step = 4001 (1.102 sec)
INFO:tensorflow:global_step/sec: 92.8716
INFO:tensorflow:loss = 2.012793, step = 4101 (1.075 sec)
INFO:tensorflow:global_step/sec: 92.2505
INFO:tensorflow:loss = 1.7874265, step = 4201 (1.085 sec)
INFO:tensorflow:global_step/sec: 90.2097
INFO:tensorflow:loss = 1.5192823, step = 4301 (1.109 sec)
INFO:tensorflow:global_step/sec: 87.6141
INFO:tensorflow:loss = 1.6895639, step = 4401 (1.140 sec)
INFO:tensorflow:global_step/sec: 87.7621
INFO:tensorflow:loss = 1.6752446, step = 4501 (1.139 sec)
INFO:tensorflow:global_step/sec: 93.9235
INFO:tensorflow:loss = 1.411518, step = 4601 (1.064 sec)
INFO:tensorflow:global_step/sec: 88.0985
INFO:tensorflow:loss = 1.302026, step = 4701 (1.135 sec)
INFO:tensorflow:global_step/sec: 90.2396
INFO:tensorflow:loss = 1.793739, step = 4801 (1.109 sec)
INFO:tensorflow:global_step/sec: 89.0218
INFO:tensorflow:loss = 1.7786595, step = 4901 (1.123 sec)
INFO:tensorflow:global_step/sec: 87.504
INFO:tensorflow:loss = 1.4372505, step = 5001 (1.142 sec)
INFO:tensorflow:global_step/sec: 87.1484
INFO:tensorflow:loss = 1.5453149, step = 5101 (1.148 sec)
INFO:tensorflow:global_step/sec: 88.904
INFO:tensorflow:loss = 1.6717218, step = 5201 (1.126 sec)
INFO:tensorflow:global_step/sec: 83.661
INFO:tensorflow:loss = 1.7141006, step = 5301 (1.196 sec)
INFO:tensorflow:global_step/sec: 80.4164
INFO:tensorflow:loss = 1.7885011, step = 5401 (1.244 sec)
INFO:tensorflow:global_step/sec: 89.2797
INFO:tensorflow:loss = 1.5996757, step = 5501 (1.122 sec)
INFO:tensorflow:global_step/sec: 88.5007
INFO:tensorflow:loss = 1.9479822, step = 5601 (1.126 sec)
INFO:tensorflow:global_step/sec: 89.8498
INFO:tensorflow:loss = 1.8109365, step = 5701 (1.114 sec)
INFO:tensorflow:global_step/sec: 89.0917
INFO:tensorflow:loss = 1.5863034, step = 5801 (1.123 sec)
INFO:tensorflow:global_step/sec: 91.186
INFO:tensorflow:loss = 1.5675447, step = 5901 (1.095 sec)
INFO:tensorflow:global_step/sec: 89.7133
INFO:tensorflow:loss = 1.9371823, step = 6001 (1.116 sec)
INFO:tensorflow:global_step/sec: 91.1682
INFO:tensorflow:loss = 1.5914541, step = 6101 (1.098 sec)
INFO:tensorflow:global_step/sec: 90.9295
INFO:tensorflow:loss = 1.6377342, step = 6201 (1.098 sec)
INFO:tensorflow:global_step/sec: 93.9883
INFO:tensorflow:loss = 1.5812101, step = 6301 (1.069 sec)
INFO:tensorflow:global_step/sec: 89.3364
INFO:tensorflow:loss = 1.8952947, step = 6401 (1.115 sec)
INFO:tensorflow:global_step/sec: 90.0512
INFO:tensorflow:loss = 1.8097222, step = 6501 (1.110 sec)
INFO:tensorflow:global_step/sec: 91.3476
INFO:tensorflow:loss = 1.4384199, step = 6601 (1.094 sec)
INFO:tensorflow:global_step/sec: 91.2148
INFO:tensorflow:loss = 1.414003, step = 6701 (1.095 sec)
INFO:tensorflow:global_step/sec: 93.7178
INFO:tensorflow:loss = 1.60606, step = 6801 (1.067 sec)
INFO:tensorflow:global_step/sec: 90.1309
INFO:tensorflow:loss = 1.6594076, step = 6901 (1.111 sec)
INFO:tensorflow:global_step/sec: 94.7648
INFO:tensorflow:loss = 1.5402876, step = 7001 (1.055 sec)
INFO:tensorflow:global_step/sec: 91.3244
INFO:tensorflow:loss = 1.6169074, step = 7101 (1.094 sec)
INFO:tensorflow:global_step/sec: 90.1828
INFO:tensorflow:loss = 1.4785136, step = 7201 (1.109 sec)

INFO:tensorflow:global_step/sec: 88.4173
INFO:tensorflow:loss = 1.5962082, step = 7301 (1.131 sec)
INFO:tensorflow:global_step/sec: 87.9755
INFO:tensorflow:loss = 1.6433401, step = 7401 (1.137 sec)
INFO:tensorflow:global_step/sec: 91.9078
INFO:tensorflow:loss = 1.6826012, step = 7501 (1.089 sec)
INFO:tensorflow:global_step/sec: 87.6513
INFO:tensorflow:loss = 1.7555861, step = 7601 (1.139 sec)
INFO:tensorflow:global_step/sec: 88.2755
INFO:tensorflow:loss = 1.8250775, step = 7701 (1.134 sec)
INFO:tensorflow:global_step/sec: 91.0319
INFO:tensorflow:loss = 1.5791428, step = 7801 (1.100 sec)
INFO:tensorflow:global_step/sec: 89.934
INFO:tensorflow:loss = 1.4345944, step = 7901 (1.112 sec)
INFO:tensorflow:global_step/sec: 90.1541
INFO:tensorflow:loss = 1.4475104, step = 8001 (1.108 sec)
INFO:tensorflow:global_step/sec: 89.0457
INFO:tensorflow:loss = 1.3728611, step = 8101 (1.123 sec)
INFO:tensorflow:global_step/sec: 91.3406
INFO:tensorflow:loss = 1.5740453, step = 8201 (1.097 sec)
INFO:tensorflow:global_step/sec: 89.7806
INFO:tensorflow:loss = 1.5392656, step = 8301 (1.115 sec)
INFO:tensorflow:global_step/sec: 91.011
INFO:tensorflow:loss = 1.6886725, step = 8401 (1.097 sec)
INFO:tensorflow:global_step/sec: 87.1212
INFO:tensorflow:loss = 1.6650604, step = 8501 (1.147 sec)
INFO:tensorflow:global_step/sec: 92.3322
INFO:tensorflow:loss = 1.5153772, step = 8601 (1.083 sec)
INFO:tensorflow:global_step/sec: 88.1589
INFO:tensorflow:loss = 1.5321982, step = 8701 (1.134 sec)
INFO:tensorflow:global_step/sec: 89.6855
INFO:tensorflow:loss = 1.4129798, step = 8801 (1.115 sec)
INFO:tensorflow:global_step/sec: 90.1678
INFO:tensorflow:loss = 1.4097039, step = 8901 (1.111 sec)
INFO:tensorflow:global_step/sec: 88.8438
INFO:tensorflow:loss = 1.8265055, step = 9001 (1.125 sec)
INFO:tensorflow:global_step/sec: 87.2619
INFO:tensorflow:loss = 1.2664429, step = 9101 (1.144 sec)
INFO:tensorflow:global_step/sec: 88.3495
INFO:tensorflow:loss = 1.4762142, step = 9201 (1.132 sec)
INFO:tensorflow:global_step/sec: 90.8565
INFO:tensorflow:loss = 1.7516366, step = 9301 (1.101 sec)
INFO:tensorflow:global_step/sec: 88.2653
INFO:tensorflow:loss = 1.538273, step = 9401 (1.134 sec)
INFO:tensorflow:global_step/sec: 92.0955
INFO:tensorflow:loss = 1.345148, step = 9501 (1.085 sec)
INFO:tensorflow:global_step/sec: 90.3399
INFO:tensorflow:loss = 1.5749614, step = 9601 (1.106 sec)
INFO:tensorflow:global_step/sec: 89.9266
INFO:tensorflow:loss = 1.8178601, step = 9701 (1.114 sec)
INFO:tensorflow:global_step/sec: 88.948
INFO:tensorflow:loss = 1.3375031, step = 9801 (1.122 sec)
INFO:tensorflow:global_step/sec: 87.4607
INFO:tensorflow:loss = 1.3535929, step = 9901 (1.149 sec)
INFO:tensorflow:global_step/sec: 88.9398
INFO:tensorflow:loss = 1.8749303, step = 10001 (1.119 sec)
INFO:tensorflow:global_step/sec: 89.4265
INFO:tensorflow:loss = 1.6115408, step = 10101 (1.118 sec)
INFO:tensorflow:global_step/sec: 89.1346
INFO:tensorflow:loss = 1.5498824, step = 10201 (1.122 sec)
INFO:tensorflow:global_step/sec: 94.3575
INFO:tensorflow:loss = 1.9823383, step = 10301 (1.060 sec)
INFO:tensorflow:global_step/sec: 88.7789
INFO:tensorflow:loss = 1.7005165, step = 10401 (1.126 sec)
INFO:tensorflow:global_step/sec: 85.4579
INFO:tensorflow:loss = 1.5058283, step = 10501 (1.171 sec)
INFO:tensorflow:global_step/sec: 84.2684
INFO:tensorflow:loss = 1.5212016, step = 10601 (1.193 sec)
INFO:tensorflow:global_step/sec: 88.1212
INFO:tensorflow:loss = 1.5698197, step = 10701 (1.129 sec)
INFO:tensorflow:global_step/sec: 89.2004
INFO:tensorflow:loss = 1.8297061, step = 10801 (1.122 sec)
INFO:tensorflow:global_step/sec: 86.9828
INFO:tensorflow:loss = 1.4522908, step = 10901 (1.149 sec)
INFO:tensorflow:global_step/sec: 87.0489
INFO:tensorflow:loss = 1.2883185, step = 11001 (1.148 sec)
INFO:tensorflow:global_step/sec: 89.6838
INFO:tensorflow:loss = 1.5830879, step = 11101 (1.115 sec)
INFO:tensorflow:global_step/sec: 90.7865
INFO:tensorflow:loss = 1.7473652, step = 11201 (1.103 sec)
INFO:tensorflow:global_step/sec: 89.2506
INFO:tensorflow:loss = 1.6361804, step = 11301 (1.120 sec)
INFO:tensorflow:global_step/sec: 88.4955
INFO:tensorflow:loss = 1.5725343, step = 11401 (1.131 sec)
INFO:tensorflow:global_step/sec: 89.8367
INFO:tensorflow:loss = 1.540935, step = 11501 (1.111 sec)
INFO:tensorflow:global_step/sec: 91.9179
INFO:tensorflow:loss = 1.7225577, step = 11601 (1.090 sec)
INFO:tensorflow:global_step/sec: 89.3506
INFO:tensorflow:loss = 1.5921772, step = 11701 (1.117 sec)
INFO:tensorflow:global_step/sec: 91.7901
INFO:tensorflow:loss = 1.9482765, step = 11801 (1.093 sec)
INFO:tensorflow:global_step/sec: 88.8128
INFO:tensorflow:loss = 1.5584291, step = 11901 (1.124 sec)
INFO:tensorflow:global_step/sec: 88.626
INFO:tensorflow:loss = 1.5987123, step = 12001 (1.127 sec)
INFO:tensorflow:global_step/sec: 91.6822
INFO:tensorflow:loss = 1.5973489, step = 12101 (1.092 sec)
INFO:tensorflow:global_step/sec: 93.9226
INFO:tensorflow:loss = 1.5992666, step = 12201 (1.063 sec)
INFO:tensorflow:global_step/sec: 93.1619
INFO:tensorflow:loss = 1.6340367, step = 12301 (1.073 sec)
INFO:tensorflow:global_step/sec: 88.4249
INFO:tensorflow:loss = 1.6581683, step = 12401 (1.132 sec)
INFO:tensorflow:global_step/sec: 88.5134
INFO:tensorflow:loss = 1.5374177, step = 12501 (1.130 sec)
INFO:tensorflow:global_step/sec: 89.2919
INFO:tensorflow:loss = 1.8030471, step = 12601 (1.121 sec)
INFO:tensorflow:global_step/sec: 90.3007
INFO:tensorflow:loss = 1.4551599, step = 12701 (1.107 sec)
INFO:tensorflow:global_step/sec: 89.5775
INFO:tensorflow:loss = 1.6216824, step = 12801 (1.115 sec)
INFO:tensorflow:global_step/sec: 89.0382
INFO:tensorflow:loss = 1.5320532, step = 12901 (1.124 sec)
INFO:tensorflow:global_step/sec: 86.6277
INFO:tensorflow:loss = 1.6158909, step = 13001 (1.153 sec)
INFO:tensorflow:global_step/sec: 89.4512
INFO:tensorflow:loss = 1.606664, step = 13101 (1.118 sec)
INFO:tensorflow:global_step/sec: 91.1113
INFO:tensorflow:loss = 1.7900939, step = 13201 (1.098 sec)
INFO:tensorflow:global_step/sec: 90.6636
INFO:tensorflow:loss = 1.5742688, step = 13301 (1.103 sec)
INFO:tensorflow:global_step/sec: 91.217
INFO:tensorflow:loss = 1.9023368, step = 13401 (1.097 sec)
INFO:tensorflow:global_step/sec: 90.6278
INFO:tensorflow:loss = 1.4838582, step = 13501 (1.103 sec)
INFO:tensorflow:global_step/sec: 90.6873
INFO:tensorflow:loss = 1.321214, step = 13601 (1.103 sec)
INFO:tensorflow:global_step/sec: 88.6277
INFO:tensorflow:loss = 1.6452286, step = 13701 (1.127 sec)
INFO:tensorflow:global_step/sec: 90.47
INFO:tensorflow:loss = 1.5737327, step = 13801 (1.106 sec)
INFO:tensorflow:global_step/sec: 89.247
INFO:tensorflow:loss = 1.5749713, step = 13901 (1.122 sec)
INFO:tensorflow:global_step/sec: 89.8422
INFO:tensorflow:loss = 1.6752114, step = 14001 (1.111 sec)
INFO:tensorflow:global_step/sec: 91.7798
INFO:tensorflow:loss = 1.5275732, step = 14101 (1.090 sec)
INFO:tensorflow:global_step/sec: 89.333
INFO:tensorflow:loss = 1.3440338, step = 14201 (1.119 sec)
INFO:tensorflow:global_step/sec: 84.7883
INFO:tensorflow:loss = 1.595128, step = 14301 (1.180 sec)
INFO:tensorflow:global_step/sec: 74.1225
INFO:tensorflow:loss = 1.7058823, step = 14401 (1.350 sec)
INFO:tensorflow:global_step/sec: 88.2718
INFO:tensorflow:loss = 1.5890106, step = 14501 (1.133 sec)
INFO:tensorflow:global_step/sec: 87.8396
INFO:tensorflow:loss = 1.7354646, step = 14601 (1.137 sec)
INFO:tensorflow:global_step/sec: 88.0473
INFO:tensorflow:loss = 1.5854485, step = 14701 (1.139 sec)
INFO:tensorflow:global_step/sec: 86.4537
INFO:tensorflow:loss = 1.501324, step = 14801 (1.153 sec)
INFO:tensorflow:global_step/sec: 89.2731
INFO:tensorflow:loss = 1.402418, step = 14901 (1.121 sec)
INFO:tensorflow:Saving checkpoints for 15000 into /tmp/tmp3a9xktor/model.ckpt.
INFO:tensorflow:Loss for final step: 1.5613813.

SKCompat()

In [53]:
# With a smaller data set of about 100,000 entries, accuracy is about 41%
# it goes down when more entries are added it seems

y_predict_hidden = dnn_clf_hidden.predict(x_test)
accuracy_score(y_test_int, y_predict_hidden['classes'])

WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
INFO:tensorflow:Restoring parameters from /tmp/tmp3a9xktor/model.ckpt-15000

0.47187263078089464

In [ ]:
y_predict_hidden_train = dnn_clf_hidden.predict(x_train)

# c = tf.confusion_matrix(y_train_int, y_predict_hidden_train['classes'])

with tf.Session():
    print('Confusion Matrix: \n\n', tf.Tensor.eval(tf.confusion_matrix(y_train_int, y_predict_hidden_train['classes']),feed_dict=None, session=None))

# Testing out some Activation Functions

Our fully connected network with 2 hidden layers didn't perform to well, so let's experiment with some activation functions!

The first alternate activation function that we will try is the sigmoid, after than we will try the tanh; in both cases the accuracy decreased from the default relu function.

In [ ]:
dnn_clf_sig = tf.contrib.learn.DNNClassifier(hidden_units = [300, 150], n_classes = 14, activation_fn="sigmoid", feature_columns = feature_cols)
dnn_clf_sig = tf.contrib.learn.SKCompat(dnn_clf_sig)
dnn_clf_sig.fit(x_train, y_train_int, batch_size = 50, steps = 10000) # 10,000 steps

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpp1pughzk
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f8ecd3f99e8>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/tmp/tmpp1pughzk'}
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/tmpp1pughzk/model.ckpt.
INFO:tensorflow:loss = 3.0548224, step = 1
INFO:tensorflow:global_step/sec: 83.0795
INFO:tensorflow:loss = 2.076484, step = 101 (1.208 sec)
INFO:tensorflow:global_step/sec: 89.8761
INFO:tensorflow:loss = 2.1376698, step = 201 (1.111 sec)
INFO:tensorflow:global_step/sec: 84.9865
INFO:tensorflow:loss = 2.241373, step = 301 (1.178 sec)
INFO:tensorflow:global_step/sec: 82.0882
INFO:tensorflow:loss = 1.9263469, step = 401 (1.218 sec)
INFO:tensorflow:global_step/sec: 84.3251
INFO:tensorflow:loss = 1.9930743, step = 501 (1.185 sec)
INFO:tensorflow:global_step/sec: 87.8841
INFO:tensorflow:loss = 1.9621086, step = 601 (1.138 sec)
INFO:tensorflow:global_step/sec: 87.4723
INFO:tensorflow:loss = 2.0232925, step = 701 (1.143 sec)
INFO:tensorflow:global_step/sec: 87.82
INFO:tensorflow:loss = 1.9651238, step = 801 (1.140 sec)
INFO:tensorflow:global_step/sec: 89.2428
INFO:tensorflow:loss = 2.117202, step = 901 (1.121 sec)
INFO:tensorflow:global_step/sec: 87.2711
INFO:tensorflow:loss = 1.7844232, step = 1001 (1.147 sec)
INFO:tensorflow:global_step/sec: 87.8274
INFO:tensorflow:loss = 1.7200884, step = 1101 (1.137 sec)
INFO:tensorflow:global_step/sec: 85.807
INFO:tensorflow:loss = 1.7656484, step = 1201 (1.165 sec)
INFO:tensorflow:global_step/sec: 87.8502
INFO:tensorflow:loss = 1.8358054, step = 1301 (1.138 sec)
INFO:tensorflow:global_step/sec: 89.2741
INFO:tensorflow:loss = 1.7570546, step = 1401 (1.120 sec)
INFO:tensorflow:global_step/sec: 87.4039
INFO:tensorflow:loss = 1.6782532, step = 1501 (1.144 sec)
INFO:tensorflow:global_step/sec: 89.3256
INFO:tensorflow:loss = 2.0675688, step = 1601 (1.119 sec)
INFO:tensorflow:global_step/sec: 86.9378
INFO:tensorflow:loss = 1.7957062, step = 1701 (1.151 sec)
INFO:tensorflow:global_step/sec: 87.9824
INFO:tensorflow:loss = 1.8632509, step = 1801 (1.144 sec)
INFO:tensorflow:global_step/sec: 87.7029
INFO:tensorflow:loss = 1.616111, step = 1901 (1.132 sec)
INFO:tensorflow:global_step/sec: 90.3421
INFO:tensorflow:loss = 1.7468438, step = 2001 (1.107 sec)
INFO:tensorflow:global_step/sec: 89.9091
INFO:tensorflow:loss = 2.017142, step = 2101 (1.112 sec)
INFO:tensorflow:global_step/sec: 86.3525
INFO:tensorflow:loss = 2.049098, step = 2201 (1.161 sec)
INFO:tensorflow:global_step/sec: 86.9791
INFO:tensorflow:loss = 1.7122983, step = 2301 (1.148 sec)
INFO:tensorflow:global_step/sec: 86.2874
INFO:tensorflow:loss = 1.5557119, step = 2401 (1.158 sec)
INFO:tensorflow:global_step/sec: 88.9896
INFO:tensorflow:loss = 1.7959564, step = 2501 (1.125 sec)
INFO:tensorflow:global_step/sec: 86.41
INFO:tensorflow:loss = 1.8019851, step = 2601 (1.159 sec)
INFO:tensorflow:global_step/sec: 90.362
INFO:tensorflow:loss = 1.8017117, step = 2701 (1.106 sec)
INFO:tensorflow:global_step/sec: 90.6096
INFO:tensorflow:loss = 1.8755598, step = 2801 (1.103 sec)
INFO:tensorflow:global_step/sec: 93.5768
INFO:tensorflow:loss = 1.8748024, step = 2901 (1.070 sec)
INFO:tensorflow:global_step/sec: 86.0494
INFO:tensorflow:loss = 1.9665861, step = 3001 (1.161 sec)
INFO:tensorflow:global_step/sec: 89.7649
INFO:tensorflow:loss = 1.93097, step = 3101 (1.114 sec)
INFO:tensorflow:global_step/sec: 88.7938
INFO:tensorflow:loss = 1.8341995, step = 3201 (1.124 sec)
INFO:tensorflow:global_step/sec: 87.873
INFO:tensorflow:loss = 1.7787063, step = 3301 (1.139 sec)
INFO:tensorflow:global_step/sec: 85.7437
INFO:tensorflow:loss = 1.6070682, step = 3401 (1.166 sec)
INFO:tensorflow:global_step/sec: 86.6543
INFO:tensorflow:loss = 1.7033175, step = 3501 (1.154 sec)
INFO:tensorflow:global_step/sec: 91.4314
INFO:tensorflow:loss = 1.7888021, step = 3601 (1.096 sec)
INFO:tensorflow:global_step/sec: 91.2739
INFO:tensorflow:loss = 1.8843484, step = 3701 (1.095 sec)
INFO:tensorflow:global_step/sec: 86.5174
INFO:tensorflow:loss = 1.7870761, step = 3801 (1.156 sec)
INFO:tensorflow:global_step/sec: 90.3803
INFO:tensorflow:loss = 1.6613426, step = 3901 (1.108 sec)
INFO:tensorflow:global_step/sec: 86.9698
INFO:tensorflow:loss = 1.6547073, step = 4001 (1.148 sec)
INFO:tensorflow:global_step/sec: 86.8946
INFO:tensorflow:loss = 2.087203, step = 4101 (1.150 sec)
INFO:tensorflow:global_step/sec: 87.5483
INFO:tensorflow:loss = 1.9374151, step = 4201 (1.144 sec)
INFO:tensorflow:global_step/sec: 90.9309
INFO:tensorflow:loss = 1.647552, step = 4301 (1.098 sec)
INFO:tensorflow:global_step/sec: 89.1446
INFO:tensorflow:loss = 1.8097142, step = 4401 (1.122 sec)
INFO:tensorflow:global_step/sec: 86.8175
INFO:tensorflow:loss = 1.7926545, step = 4501 (1.153 sec)
INFO:tensorflow:global_step/sec: 85.243
INFO:tensorflow:loss = 1.4940988, step = 4601 (1.173 sec)
INFO:tensorflow:global_step/sec: 89.1425
INFO:tensorflow:loss = 1.3666732, step = 4701 (1.120 sec)
INFO:tensorflow:global_step/sec: 87.6737
INFO:tensorflow:loss = 1.7699733, step = 4801 (1.143 sec)
INFO:tensorflow:global_step/sec: 85.9437
INFO:tensorflow:loss = 1.6520694, step = 4901 (1.162 sec)
INFO:tensorflow:global_step/sec: 87.7722
INFO:tensorflow:loss = 1.6295671, step = 5001 (1.139 sec)
INFO:tensorflow:global_step/sec: 88.0485
INFO:tensorflow:loss = 1.6418947, step = 5101 (1.136 sec)
INFO:tensorflow:global_step/sec: 86.4739
INFO:tensorflow:loss = 1.7988037, step = 5201 (1.158 sec)
INFO:tensorflow:global_step/sec: 86.7776
INFO:tensorflow:loss = 1.7270651, step = 5301 (1.151 sec)
INFO:tensorflow:global_step/sec: 89.2242
INFO:tensorflow:loss = 1.8338311, step = 5401 (1.122 sec)
INFO:tensorflow:global_step/sec: 87.9205
INFO:tensorflow:loss = 1.5400915, step = 5501 (1.137 sec)
INFO:tensorflow:global_step/sec: 88.0152
INFO:tensorflow:loss = 1.9415816, step = 5601 (1.136 sec)
INFO:tensorflow:global_step/sec: 88.7615
INFO:tensorflow:loss = 1.9041121, step = 5701 (1.126 sec)
INFO:tensorflow:global_step/sec: 87.9836
INFO:tensorflow:loss = 1.8056855, step = 5801 (1.136 sec)
INFO:tensorflow:global_step/sec: 85.0592
INFO:tensorflow:loss = 1.5789804, step = 5901 (1.177 sec)
INFO:tensorflow:global_step/sec: 84.4843
INFO:tensorflow:loss = 1.9278846, step = 6001 (1.184 sec)
INFO:tensorflow:global_step/sec: 84.5885
INFO:tensorflow:loss = 1.7494729, step = 6101 (1.182 sec)
INFO:tensorflow:global_step/sec: 86.6981
INFO:tensorflow:loss = 1.8040897, step = 6201 (1.154 sec)

In [ ]:
y_predict_sig = dnn_clf_sig.predict(x_test)
accuracy_score(y_test_int, y_predict_sig['classes'])

## Now let's try out tanh activation function

In [ ]:
dnn_clf_tanh = tf.contrib.learn.DNNClassifier(hidden_units = [300, 150], n_classes = 14, activation_fn="tanh", feature_columns = feature_cols)
dnn_clf_tanh = tf.contrib.learn.SKCompat(dnn_clf_tanh)
dnn_clf_tanh.fit(x_train, y_train_int, batch_size = 50, steps = 15000) # 10,000 steps

In [ ]:
y_predict_tanh = dnn_clf_tanh.predict(x_test)
accuracy_score(y_test_int, y_predict_tanh['classes'])

# Tweaking the Model Parameters to Improve Performance

In [ ]:
x_test.info()

# Execution Phase of DNN

In [ ]:
len(y_train) # This is the amount of times we will need to iterate through later

In [ ]:
len(train_set)

In [ ]:
# n_epochs = 40
# batch_size = 50
# init=tf.global_variables_initializer()

In [ ]:
# with tf.Session() as sess:
#     init.run()
#     for epoch in range(n_epochs):
#         for iteration in range(len(train_set) // batch_size):
#             x_batch = x_train.next_batch(batch_size)
#             y_batch = y_train_int.next_batch(batch_size)
#             sess.run(training_op, feed_dict = {X: x_batch, y: y_batch})
#         acc_train = accuracy.eval(feed_dict = {X: x_batch, y: y_batch})
#         acc_test = accuracy.eval(feed_dict = {X: x_test, y: y_test_int})
#         print(epoch, "Train Accuracy:", acc_train, "Test Accuracy:", acc_test)
    
#     save_path = saver.save(sess, "./my_model_final.ckpt")